version: '3'
services:

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

  web:
    build: .
    ports:
     - "8000:8000"
    depends_on:
     - "redis"
    volumes:
      - ./:/all
    environment:
      - REDIS_HOST=redis
    command: uvicorn --debug --host 0.0.0.0 web:api
  
  worker:
    build: .
    depends_on:
     - "redis"
    volumes:
      - ./:/all
    environment:
      - REDIS_HOST=redis
    command: huey_consumer.py worker.redis_queue.huey -k process -w 1
